openapi: 3.0.0

info:
  title: Reach Backend API
  version: 0.0.1-SNAPSHOT
  description: |         
    This is the API specification for the endpoints included in the Reach web app backend.


paths:
  /health:
    get:
      tags:
        - Health
      summary: Ping backend health
      description: Call this endpoint to check if the backend is up and running.
      operationId: checkHealth
      responses:
        '200':
          description: Backend is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorld'
        '401':
          description: Health error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorldError'
        '500':
          description: Internal server error


components:
  schemas:
    HelloWorld:
      type: object
      description: Default health response
      properties:
        message:
          type: string
        timestamp:
          type: string
          format: date-time
    HelloWorldError:
      type: object
      description: Health error
      properties:
        error:
          type: string
        randomNumber:
          type: number