openapi: 3.0.0

info:
  title: Reach Backend API
  version: 0.0.1-SNAPSHOT
  description: |         
    This is the API specification for the endpoints included in the Reach web app backend.


paths:
  /health:
    get:
      tags:
        - Health
      summary: Ping backend health
      description: Call this endpoint to check if the backend is up and running.
      operationId: checkHealth
      responses:
        '200':
          description: Backend is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorld'
        '401':
          description: Health error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorldError'
        '500':
          description: Internal server error
  /Brand:
    post:
      tags:
        - Brand
      summary: Add a new Brand
      description: Call this endpoint to add a new Brand to the database
      operationId: add Brand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrandCreation'
      responses:
        '200':
          description: Brand successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrandCreation'
        '401':
          description: Brand not created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrandCreationError'
        '500':
          description: Internal or External server error


components:
  schemas:
    HelloWorld:
      type: object
      description: Default health response
      properties:
        message:
          type: string
        timestamp:
          type: string
          format: date-time
    HelloWorldError:
      type: object
      description: Health error
      properties:
        error:
          type: string
        randomNumber:
          type: number
    BrandCreation:
      type: object
      required:
        - name
        - logo
      description: Brand created on the frontend level containing all details
      properties:
        id:
          type: number
          readOnly: true
        name:
          type: string
        logo:
          type: string
          format: uri
    BrandCreationError:
      type: object
      description: Failed to create a brand
      properties:
        error:
          type: string
        randomNumber:
          type: number